### DISCUSSION TITLE
Signing RGB consignments

### DISCUSSION THREAD

**Discussion by dr-orlovsky** [RGB-WG/rgb#50] [Ideas]
We deliberately excluded signatures from RGB genesis as a part of the consensus layer. However, on the level of the standard library, I think the signatures has to be present.

My understanding is that all consignment types should allow signatures to be optionally attached to any of a contract operation item, like genesis, state transition or extension. This will allow issuers to sign genesis _and_ all secondary issuance transitions. The signatures would not participate consensus or consignment validation, but the node should report the wallet if the consignment issue data were signed and were the signatures valid - as well as provide keys for identities which made signatures.

This is why it is not the consignment as a whole which should be signed, but a specific operations (not even bundles) - i.e. the signature should be made over their `NodeId`.

Node should report the list of signed ids for each processed consignment, like
```console
$ rgb consignment info --interface rgb20
```
giving output of
```yaml
invalid_signatures:
    - id: <key_data>
      type: secp256k1
      protocol: RGB22 # or GPG
      nodeIds: [ ] # List of signed node IDs
signatures:
    - id: <key_data>
      type: secp256k1
      protocol: RGB22 # or GPG
      nodeIds: [ ] # List of signed node IDs
```
