### ISSUE TITLE
Contract state after issuance shows human-unreadable owned amount

### ISSUE THREAD

**Issue by nicbus** [RGB-WG/rgb#209]
I have updated `rgb-sandbox` to the `0.11.0-beta.6` version of `rgb-wallet` and `rgb-schemata`.

The run proceeds up to the issuance, which completes with success, but then the
contract state doesn't show the correct owned amount.

This is the used contract yaml:
```
interface: RGB20Fixed

globals:
  spec:
    ticker: USDT
    name: USD Tether
    details: ~
    precision: 0
  terms:
    text: demo NIA asset
    media: ~
  issuedSupply: 2000

assignments:
  assetOwner:
    seal: opret1st:68d478417c6fa5f6382c37f53cc9d53dd6123eee78b845330a6230c85664bbb8:0
    amount: 2000
```

This is the issuance command:
```
$ rgb-wallet/bin/rgb -n regtest --electrum=localhost:50001 -d data0 issue -w wallet_0 'KzMZV9bO7gFhox97!klj0FonG2ZKnjuOIg2tFChu$YA#lucas-episode-silicon' ssi:wallet_0 contracts/usdt.yaml

A new contract rgb:sZdo3p$Z-Krwmb1e-3S!4ITe-sOj6rhq-SzSJRu1-0H77oes is issued and added to the stash.
Use `export` command to export the contract.
```

This is the contract state after issuance:
```
$ rgb-wallet/bin/rgb -n regtest --electrum=localhost:50001 -d data0 state -w wallet_0 'rgb:sZdo3p$Z-Krwmb1e-3S!4ITe-sOj6rhq-SzSJRu1-0H77oes' RGB20Fixed

Loading descriptor from wallet wallet_0 ... success

Global:
  spec := (ticker=("USDT"), name=("USD Tether"), details=~, precision=0)
  terms := (text=("demo NIA asset"), media=~)
  issuedSupply := (2000)

Owned:
  assetOwner:
    value=TadF, utxo=bc:opret1st:68d478417c6fa5f6382c37f53cc9d53dd6123eee78b845330a6230c85664bbb8:0, witness=~
```

These are the unspents after the issuance:
```
$ rgb-wallet/bin/rgb -n regtest --electrum=localhost:50001 -d data0 utxos -w wallet_0
Loading descriptor from wallet wallet_0 ... success

Height     Amount, ṩ    Outpoint
bcrt1qczcwdghm2m7vma5p6m82jg6xgv9lfkhwtzha0s    &9/0
104        100000000    68d478417c6fa5f6382c37f53cc9d53dd6123eee78b845330a6230c85664bbb8:0

Loading descriptor from wallet wallet_0 ... success

Wallet total balance: 100000000 ṩ
```

This is the data directory for wallet 0:
[wallet_0.tar.gz](https://github.com/user-attachments/files/15765961/wallet_0.tar.gz)
