### ISSUE TITLE
Tracking: combined tapret/opret bundles in one transfer

### ISSUE THREAD

**Issue by dr-orlovsky** [RGB-WG/rgb#258]
```yaml
affects: [ v0.11.0-beta.6, v0.11.0-beta.7, v0.11.0-beta.8 ]
status: Fix proposed
layers: [ bp-dbc, bp-seals, rgb-core, rgb-std, rgb-wallet ]
```

Transfers involving combinations of simultaneous opret and tapret commitments remain unstable

## Related issues

- https://github.com/RGB-WG/rgb-std/issues/246
- https://github.com/RGB-WG/rgb-std/issues/247
- https://github.com/RGB-WG/rgb-std/issues/271
- https://github.com/RGB-WG/rgb-std/issues/275

### Round 1

- https://github.com/RGB-WG/rgb-std/pull/248
- https://github.com/RGB-WG/rgb-std/pull/252
- https://github.com/RGB-WG/rgb-std/pull/256

### Round 2

- https://github.com/RGB-WG/rgb-std/pull/272

### Round 3

- https://github.com/BP-WG/bp-core/pull/105
- https://github.com/BP-WG/bp-std/pull/50
- https://github.com/RGB-WG/rgb-core/pull/271
- https://github.com/RGB-WG/rgb-std/pull/277

## Tests

- https://github.com/RGB-WG/rgb-tests/pull/6 (original test revealing initial issue, later updated to expose further issues)
- https://github.com/RGB-WG/rgb-tests/pull/16
- https://github.com/RGB-WG/rgb-tests/pull/18
- https://github.com/RGB-WG/rgb-tests/pull/19 (combined fix for this and other issues)
