### ISSUE TITLE
Tracking: operation and state consensus ordering

### ISSUE THREAD

**Issue by dr-orlovsky** [RGB-WG/rgb#260]
```yaml
affects: v0.10.*, v0.11.*
status: Fix proposed
breaks: [ rgb-core, rgb-std, rgb-wallet ]
```

## Proposals

- [RCP-240731A](https://github.com/RGB-WG/RFC/issues/10)
- [RCP-241013A](https://github.com/RGB-WG/RFC/issues/13)

## Issues

- https://github.com/RGB-WG/rgb-core/issues/117
- https://github.com/RGB-WG/rgb-core/issues/273

### Base implementation

- https://github.com/RGB-WG/rgb-core/issues/117

### Bugfix Round 1

- https://github.com/RGB-WG/rgb-core/pull/169
- https://github.com/RGB-WG/rgb-std/pull/85

### Bugfix Round 2

- https://github.com/RGB-WG/rgb-core/pull/267
- https://github.com/RGB-WG/rgb-std/pull/260

### Bugfix Round 3

- https://github.com/RGB-WG/rgb-core/pull/274
- https://github.com/RGB-WG/rgb-core/pull/275
