### ISSUE TITLE
Tracking: state unification, removal of confidential assets

### ISSUE THREAD

**Issue by dr-orlovsky** [RGB-WG/rgb#263]
```yaml
affects: 0.11.0-beta.9
status: wip
breaks: [ rgb-core, rgb-std, rgb-wallet, rgb-schemata, rgb-interfaces ]
```

## Goals

- Remove Pedersen commitments and bulleproofs
- Unify all types of owned state (structured, fungible, attachments, rights)
- Remove state concealements

## Proposals

- WIP

## Issues

n/a

## Pull requests

- https://github.com/RGB-WG/rgb-core/pull/279
- https://github.com/RGB-WG/rgb-std/pull/279
- https://github.com/RGB-WG/rgb/pull/262
- TBD in `rgb-interfaces`
- TBD in `rgb-schemata`
- TBD in `rgb-tests`
